microsoft/dotnet-podcasts

docs/demos/azurecontainerapps/MessageCount.ps1
docs/demos/azurecontainerapps/Readme.md

query messages in queue for container apps demo

---

Directory.build.props
src/Mobile/Microsoft.NetConf2021.Maui.csproj
src/Mobile/Platforms/Android/Services/MediaPlayerService.cs
src/Mobile/Services/EssentialsExtensions.cs
src/MobileBlazor/mauiapp/NetPodsMauiBlazor.csproj
src/Services/ListenTogether/ListenTogether.Application/ListenTogether.Application.csproj
src/Services/ListenTogether/ListenTogether.Hub/ListenTogether.Hub.csproj
src/Services/ListenTogether/ListenTogether.Infrastructure/ListenTogether.Infrastructure.csproj
src/Services/Podcasts/Podcast.API/Podcast.API.csproj
src/Services/Podcasts/Podcast.Infrastructure/Podcast.Infrastructure.csproj
src/Services/Podcasts/Podcast.Ingestion.Worker/Podcast.Ingestion.Worker.csproj
src/Services/Podcasts/Podcast.Updater.Worker/Podcast.Updater.Worker.csproj
src/Web/Client/Podcast.Client.csproj
src/Web/Components/Podcast.Components.Maui.csproj
src/Web/Components/Podcast.Components.csproj
src/Web/Pages/Podcast.Pages.Maui.csproj
src/Web/Pages/Podcast.Pages.csproj
src/Web/Server/Podcast.Server.csproj

Bump .NET MAUI P11 final version

---

src/Web/Server/Pages/Landing.cshtml

Looked through and didn't spot anything else! :)

Fix typo "includiung" -> "including"

---

src/Services/ListenTogether/ListenTogether.Application/Rooms/LeaveRoomRequestHandler.cs
src/Services/ListenTogether/ListenTogether.Domain/Room.cs

Thank you very much for this app. I have got new skills and ideas. Can I make it app a little better? I think my renaming will make this project even better :)
I wish you good luck with the development of the application!

Rename Empty -> IsEmpty in Room

---

src/Mobile/Platforms/Android/MainActivity.cs

"Initialize" was spelled incorrectly.

Fix typo of "InitilizeMedia" in MainActivity

---

.github/workflows/podcast-mobile.yml
src/Mobile/Pages/CategoriesPage.xaml
src/Mobile/Platforms/Android/Services/MediaPlayerService.cs
src/Mobile/Resources/Styles/DefaultTheme.xaml

Right now, we don't really have CI for the mobile app, so this at least verifies the project builds.

Setup Github actions for the Mobile project

---

src/Mobile/MauiProgram.cs
src/Mobile/Pages/DiscoverPage.xaml
src/Mobile/Services/ServicesExtensions.cs
src/MobileBlazor/mauiapp/MauiProgram.cs

These changes are necessary to compile the code with maui p14.
References in: https://github.com/dotnet/maui/wiki/Migrating-to-Preview-14

Migrate to p14

---

NuGet.config

Add a nuget.config that adds the necessary feeds.
See https://docs.microsoft.com/en-us/nuget/concepts/security-best-practices#nuget-feeds
cc @jonathanpeppers

Fix CI build

---

deploy/Services/api.deployment.json

Namespace migration from Microsoft.Web to Microsoft.App
Ref: https://github.com/microsoft/azure-container-apps/issues/109
>this needs a review before merge.

ARM deployment - Migrate Microsoft.Web to Microsoft.App

---

.github/workflows/podcast-hub.yml
.github/workflows/podcast-web.yml

Fixes changes related to Azure Container Apps configuration query

Fix API Query

---

.github/workflows/podcast-hub.yml
deploy/Services/hub.deployment.json

Fixes https://github.com/microsoft/dotnet-podcasts/issues/83

Fix Orleans Storage

---

README.md

Use dot.net link now that we have the landing page for MAUI

Update MAUI link

---

src/MobileBlazor/mauiapp/Platforms/Android/AndroidManifest.xml
src/MobileBlazor/mauiapp/Platforms/Android/Resources/xml/network_security_config.xml

https://github.com/microsoft/dotnet-podcasts/issues/102

Play audio without https on android-blazor

---

src/Mobile/Converters/TextToTypeTextConverter.cs
src/Mobile/Pages/EpisodeDetailPage.xaml

The content of Episode.Description is not of type html always.  
I will close this issue. https://github.com/microsoft/dotnet-podcasts/issues/100

Add converter to detect is html content on Episode.Detail

---

src/Mobile/ViewModels/ListenLaterViewModel.cs
src/Mobile/ViewModels/SubscriptionsViewModel.cs

Now we force replace all list.

Listen later and subcription lists only appear first time on macos

---

src/Mobile/Pages/ListenLaterPage.xaml
src/Mobile/Pages/SubscriptionsPage.xaml
src/Mobile/Pages/SubscriptionsPage.xaml.cs
src/Mobile/ViewModels/ListenLaterViewModel.cs
src/Mobile/ViewModels/SubscriptionsViewModel.cs

We now use CollectionView.EmptyView when there are no elements.

Use CollectionView.EmptyView

---

src/Mobile/Views/ShowItemView.xaml
src/Mobile/Views/ShowItemView.xaml.cs

Waiting StateLayout into community toolkit maui

show activity indicator by the moment. 

---

.github/workflows/podcast-web-pr.yml
docs/demos/playwright-tests/README.md
src/Web/E2E/package-lock.json
src/Web/E2E/package.json
src/Web/E2E/playwright.config.ts
src/Web/E2E/tests/discover.spec.ts
src/Web/E2E/tests/settings.spec.ts

- upgrade to 1.26
- move for each loops to test case level for increased parallelism
- run tests on Microsoft Edge

E2E test improvements

---

src/MobileBlazor/mauiapp/NetPodsMauiBlazor.csproj
src/Services/Podcasts/Podcast.MinimalAPI/Routes/EpisodesApi.cs
src/Services/Podcasts/Podcast.MinimalAPI/appsettings.Development.json
src/Web/Client/Podcast.Client.csproj
src/Web/Components/Podcast.Components.csproj
src/Web/Pages/Podcast.Pages.csproj
src/Web/Server/Podcast.Server.csproj

Fixes some issues with the blazor app

Bump more packages to .nET7

---

docker-compose.override.yml
src/Services/ListenTogether/ListenTogether.Application/ListenTogether.Application.csproj
src/Services/ListenTogether/ListenTogether.Hub/ListenTogether.Hub.csproj
src/Services/ListenTogether/ListenTogether.Hub/appsettings.Development.json
src/Services/ListenTogether/ListenTogether.Infrastructure/ListenTogether.Infrastructure.csproj
src/Services/Podcasts/Podcast.API/appsettings.Development.json
src/Services/Podcasts/Podcast.Infrastructure/Podcast.Infrastructure.csproj
src/Services/Podcasts/Podcast.Ingestion.Worker/appsettings.Development.json
src/Services/Podcasts/Podcast.Updater.Worker/appsettings.Development.json

https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#encrypt-true

Updates for SQL and EF7 Fixes #183

---

.github/workflows/podcast-web.yml
src/Web/E2E/package-lock.json
src/Web/E2E/package.json
src/Web/E2E/tests/discover.spec.ts
src/Web/E2E/tests/listen-later.spec.ts
src/Web/E2E/tests/listen-together.spec.ts
src/Web/E2E/tests/login.spec.ts
src/Web/E2E/tests/settings.spec.ts
src/Web/E2E/tests/subscriptions.spec.ts

- update to 1.28.1
- touch up selectors

Playwright updates

---

.github/workflows/template-api.yml
.github/workflows/template-hub.yml
.github/workflows/template-web.yml

Fixes Yaml Powershell tasks for bicep deployment with variables with '$'

---

src/Web/Pages/Events/EventHandlers.cs

There was I typo in class EventHandlers.cs that I fixed

Changed miss-typed event args type from TimeUpdateEventArgs to PlaybackRateChangeEventArgs

---

src/Web/Server/Pages/Landing.cshtml

I've made these links into buttons that are already in use around site, they should increase visibility.

Link decoration does not return after being set to none #28
