src/Mobile/Platforms/Android/AndroidManifest.xml, src/Mobile/Platforms/Android/MainActivity.cs, src/MobileBlazor/mauiapp/Platforms/Android/AndroidManifest.xml
So if this sample is meant to make web requests, it doesn't have the Android permission to do so!
This probably works fine in Debug mode, because we add the permission for you. Debugging requires it.
I also cleaned up a bit of the code setting up the media player. It seems like we were just calling into Java over and over, and I could simplify it.
=> [android] INTERNET permission + minor media player fixes

src/Mobile/MauiProgram.cs, src/Mobile/Pages/PagesExtensions.cs
There are (potentially) breaking Shell DI changes coming in .NET MAUI Preview 14.
If you want dependency injection to work with Shell pages, you need to register the page classes as well as their injected dependencies. Otherwise, you'll have to provide a parameterless constructor for any pages you don't register with the IoC container.
This PR has backwards-compatible changes that should prevent any problems once upgrading .NET MAUI to P14 and later.
=> Support Shell DI changes in .NET MAUI P14

src/Mobile/Microsoft.NetConf2021.Maui.csproj, src/Mobile/Services/ServicesExtensions.cs, src/Mobile/Services/ShowsService.cs
See https://github.com/dotnet/runtime/issues/66863 for reasoning. Using Microsoft.Extensions.Http is too heavy-weight for mobile usages, and doesn't provide any real value in this situation.
cc @jamesmontemagno @jonathanpeppers
=> Remove Microsoft.Extensions.Http from dotnet-podcasts

src/Mobile/Blazor/ListenTogetherComponent.razor, src/Mobile/Helpers/Settings.cs, src/Mobile/Helpers/TheTheme.cs, src/Mobile/ViewModels/SettingsViewModel.cs
OSAppTheme has been renamed to AppTheme, this ensures that renaming doesn't file builds.
=> Rename OSAppTheme to AppTheme.

.github/workflows/podcast-mobile.yml, src/Mobile/MauiProgram.cs, src/Mobile/Resources/Styles/DefaultTheme.xaml
We have the maui/perf branch tracking dotnet/maui/main, so we need to actually install different versions of the workloads.
dotnet-podcasts/main is tracking the latest release, .NET MAUI Preview 14 at this time.
=> [mobile] install dotnet/maui/main on maui/perf

src/Mobile/Services/ShowsService.cs, src/Mobile/ViewModels/DiscoverViewModel.cs
This allows for faster startup because initializing and checking the cache doesn't block the UI thread.
On my Pixel5a, launching the app 10 times and averaging startup times with this change:
Average(ms): 843.7
Average(ms): 847.8
Average(ms): 817.2
Average(ms): 812.8
=> Run GetShowsAsync in the background

src/Mobile/Microsoft.NetConf2021.Maui.csproj, src/Mobile/Services/ShowsService.cs
This reduces the size of the app because Newtonsoft and all the code it roots (XML, System.Data.Common) can now be trimmed. We are currently paying "double" for JSON serialization because the app uses both. MonkeyCache v1.x uses Newtonsoft. ASP.NET uses System.Text.Json.
iOS .ipa size:
29.3 MB (30,756,059 bytes)
26.1 MB (27,389,394 bytes)
=> Use System.Text.Json instead of Newtonsoft.

NuGet.config
Ensure main's CI build only uses nuget.org feed. Since main represents the latest released version, only public packages on nuget.org should be needed.
See https://docs.microsoft.com/en-us/nuget/concepts/security-best-practices#nuget-feeds
=> Fix CI build

.github/workflows/podcast-mobile.yml
Since #65 added a NuGet.config to the root of the repo, the GH action is clobbering this file. So when we run in CI we aren't using the same NuGet.config file as a "normal" dev would use.
Moving the NuGet.config file used by `workload install` to avoid this conflict.
=> Move workload install NuGet.config file so it doesn't overwrite repo's NuGet.config

src/Mobile/Pages/ListenLaterPage.xaml, src/Mobile/Pages/SettingsPage.xaml, src/Mobile/ViewModels/EpisodeViewModel.cs, src/Mobile/ViewModels/SettingsViewModel.cs, src/Mobile/Views/EpisodeItemView.xaml, src/Mobile/Views/EpisodeItemView.xaml.cs
With the changes to the maui api, the listen later page was broken. This pr fixes the layout.
=> listen later layout

src/Mobile/Models/Responses/ShowResponse.cs, src/Mobile/Models/Show.cs, src/Mobile/ViewModels/DiscoverViewModel.cs
We now group the podcasts as the web project does. 
Now it doesn't show the category headers if the list is empty in searches.
=> Dynamic podcast grouping

src/Mobile/Controls/HeaderControl.xaml, src/Mobile/Pages/ShowDetailPage.xaml
With .NET MAUI RC2. Some grid do not look good.
Screenshots:
Before:
After (with fix):
=> fix grid size

src/Mobile/Controls/Player.xaml, src/Mobile/Controls/Player.xaml.cs
We have a crash on IOS when app is launched.
Adding the height by code avoids this bug.
=> fix ios lauch

src/Mobile/Resources/Styles/DefaultTheme.xaml
We need to show the navigation bar in macOS so that the back button appears.
Now, we can navigate to back.
=> Show nav bar on macos

src/Mobile/Controls/HeaderControl.xaml, src/Mobile/Controls/Player.xaml, src/Mobile/Pages/ShowDetailPage.xaml
Some views were not visible because a label was used that does not exist. This has been replaced with the correct tag.
OLD TAG: macos
NEW TAG: macCatalyst
=> Replace macos by MacCatalyst

src/Mobile/Pages/DiscoverPage.xaml
This PR is a temporary workaround: [MacOS - CollectionView with grouping + GridItemsLayout does not load.](https://github.com/dotnet/maui/issues/6848)
https://github.com/dotnet/maui/issues/6848
In the future we will use Flexlayout but now we are in this discussion here: https://github.com/microsoft/dotnet-podcasts/pull/90
Merge only if necessary.
@jamesmontemagno @maddymontaquila
=> workaround on macos - Issue #90 

README.md
Adding metadata so this shows up in https://docs.microsoft.com/en-us/samples/browse/
NOTE: We don't have `dotnet-maui` in the docs taxonomy yet, so I used `xamarin`. We may want to wait until the taxonomy update is completed.
=> Add samples frontmatter for docs code samples

src/Web/Pages/Shared/Player/Audio.razor
fixed audio over all platforms. oncanplay plays episode twice and loadingUrl doesnt load into iPhone by oncanplay method.
Issue: https://github.com/microsoft/dotnet-podcasts/issues/123
=> fixed audio over all platforms

README.md, docker-compose.arm64.yml, docker-compose.dcproj
As we don't have a Microsoft SQL Server docker image available yet to the Apple silicon (arm64), I added the *azure-sql-edge (arm64)* as a lightweight solution, on a specific docker-compose for this architecture.
=> Add docker support for the Apple Silicon architecture

.github/workflows/podcast-web-pr.yml, .github/workflows/podcast-web.yml, .gitignore, README.md, docs/demos/playwright-tests/README.md, src/Web/E2E/package-lock.json, src/Web/E2E/package.json, src/Web/E2E/playwright.config.ts, src/Web/E2E/tests/discover.spec.ts, src/Web/E2E/tests/listen-later.spec.ts, src/Web/E2E/tests/listen-together.spec.ts, src/Web/E2E/tests/login.spec.ts, src/Web/E2E/tests/settings.spec.ts, src/Web/E2E/tests/subscriptions.spec.ts
Added 7 [Playwright ](https://playwright.dev/) e2e test cases that are executed in "podcast web CI/CD workflow", across chromium, firefox, and webkit. Base URL of the site under test is set via env variable `BASEURL`. For GHA, this value is constructed using `WEBAPP_NAME` variable.
GHA is configured to generate a test job summary and upload artifacts for HTML reports with video and trace files that can be downloaded to assist with post-mortem debugging.
Example failed test GHA run here: https://github.com/MarcusFelling/dotnet-podcasts/actions/runs/3055457978/attempts/1#summary-8358350472
=> add playwright e2e tests

.github/workflows/podcast-mobile.yml
CI is failing with:
Workload installation failed: Could not find workload 'microsoft-net-runtime-android-net6' extended by workload 'android' in manifest 'microsoft.net.sdk.android'
This is likely caused by using .NET 7 Preview 6.
Update the `dotnet-install` command to install the latest 7.0.1xx SDK.
=> [ci] updates for .NET 7 / maui builds

src/Services/Podcasts/Podcast.MinimalAPI/Podcast.MinimalAPI.csproj, src/Services/Podcasts/Podcast.MinimalAPI/Program.cs, src/Services/Podcasts/Podcast.MinimalAPI/Routes/CategoriesApi.cs, src/Services/Podcasts/Podcast.MinimalAPI/Routes/EpisodesApi.cs, src/Services/Podcasts/Podcast.MinimalAPI/Routes/FeedsApi.cs, src/Services/Podcasts/Podcast.MinimalAPI/Routes/ShowsApi.cs, src/Services/Podcasts/Podcast.MinimalAPI/appsettings.Development.json
Updates new minimal APIs app to:
- Configure Azure AD-based authentication
- Set endpoint names on all routes
- Update OpenAPI document title
cc: @baronfel Heads up as we'll need to update the deployment scripts to funnel through the Azure AD configuration.
=> Add endpoint names and setup Azure AD auth

src/Mobile/Resources/Strings/AppResource.Designer.cs, src/Mobile/Resources/Strings/AppResource.resx
=> Fix "Oops" Typo

src/Services/Podcasts/Podcast.API/Program.cs, src/Services/Podcasts/Podcast.Infrastructure/Http/ShowClient.cs
This is a PR that relates to an [issue opened by me](https://github.com/microsoft/dotnet-podcasts/issues/209).
Basically, for demo purposes, a delay is taking place before sending an HTTP request.
It was done for the logs to be seen clearly.
In this PR this part of the code is removed to optimize time processing.
=> Removed a JitterHandler because of perf issue

src/Mobile/Blazor/ListenTogetherComponent.razor, src/Mobile/Helpers/TheTheme.cs, src/Mobile/Messaging/ChangeThemeNotification.cs, src/Mobile/Messaging/LeaveRoomNotification.cs, src/Mobile/Pages/ListenTogetherPage.xaml.cs
The `MessagingCenter` component in .NET MAUI has been deprecated and the suggested replacement is the MVVM Community Toolkit `IMessenger` components. This code replaces the current usage of `MessagingCenter` with the `WeakReferenceMessenger` implementation.
=> Replaces MessagingCenter with Messenger

src/Mobile/Microsoft.NetConf2021.Maui.csproj, src/Mobile/Pages/EpisodeDetailPage.xaml, src/Mobile/Pages/ShowDetailPage.xaml, src/Mobile/Services/ImageProcessingService.cs, src/Mobile/Services/ServicesExtensions.cs, src/Mobile/ViewModels/CategoryViewModel.cs, src/Mobile/ViewModels/DiscoverViewModel.cs, src/Mobile/ViewModels/EpisodeDetailViewModel.cs, src/Mobile/ViewModels/ShowDetailViewModel.cs, src/Mobile/ViewModels/ShowViewModel.cs, src/Mobile/ViewModels/SubscriptionsViewModel.cs, src/Mobile/Views/ShowItemView.xaml, src/Mobile/Views/ShowItemView.xaml.cs
This is to help with further image compression and resizing for better overall performance.
Some of the images for the podcasts are quite large (around 3000x3000). The introduced service will resize the images to roughly 250x250 and perform additional compression (80%) of the original. This results in far better scrolling and loading performance.
=> Image Processing Service

NuGet.config, src/Mobile/Blazor/ListenTogetherComponent.razor, src/Mobile/Helpers/TheTheme.cs, src/Mobile/Microsoft.NetConf2021.Maui.csproj, src/Mobile/Pages/ListenTogetherPage.xaml.cs, src/Mobile/ViewModels/ShowDetailViewModel.cs, src/Mobile/ViewModels/SubscriptionsViewModel.cs
Context: https://github.com/dotnet/maui/pull/12885/files
The main breaking change is that `MessagingCenter` is now `internal` / in the process of being removed.
Migrate to the messenger in the Community Toolkit instead.
I also updated the `NuGet.config` for the dotnet8 feed.
=> Fix .NET 8 build errors

docs/demos/azure-monitor/README.md
Adds a guide for configuring AppInsights and enabling it for the service.
=> Guide for configuring Azure Monitor

docs/deploy-websites-services.md
Without adding this provider we hit an error.
Having it here will help others add it ahead of time without having to wait for the action to fail
=> Added missing provider registration required for azure deployment

.github/workflows/podcast-mobile.yml, NuGet.config, src/Mobile/Controls/HeaderControl.xaml, src/Mobile/Controls/Player.xaml, src/Mobile/Controls/Player.xaml.cs, src/Mobile/Pages/ShowDetailPage.xaml
Context: https://github.com/dotnet/maui/pull/5611
Fixes: https://github.com/microsoft/dotnet-podcasts/issues/239
The `net8.0` branch currently fails to build with:
src/Mobile/Controls/Player.xaml.cs(54,9): error CS0103: The name 'podcastImage' does not exist in the current context
src/Mobile/Controls/Player.xaml.cs(55,9): error CS0103: The name 'duration' does not exist in the current context
We think that `x:Name` in .NET 8 appropriately "skips" emitting fields when used in combination with `<OnPlatform/>`.
We can condition the C# code accessing these files with `#if WINDOWS || MACCATALYST` to solve this.
There are also a lot places using `<On Platform="UWP, macOS">`, we could consider cleaning these up in a future PR.
=> [net8.0] fix C# compiler error involving `x:Name`
